login: &login
  adapter: postgresql
  encoding: utf8
  host: localhost
  username: stels
  password: 123456

development:
  <<: *login
  database: subscribe_payments_stels_development

test:
  <<: *login
  database: subscribe_payments_stels_test

production:
  <<: *login
  database: subscribe_payments_stels_production